Repository gdsfactory/kfactory, pull requests merged in 2024-11, with the labels that each got.

#508 fix cli arg
  src/kfactory/cli/build.py
Labels: bug

#514 Add Instance.purpose
  src/kfactory/kcell.py
  src/kfactory/routing/optical.py
Labels: enhancement, routing

#516 fix: MetaData type alias and __all__ exports
  src/kfactory/kcell.py
Labels: bug

#518 at least partially fix the fill_tiled error
  src/kfactory/utils/fill.py
Labels: bug

#519 clean the name in kf show
  src/kfactory/kcell.py
Labels: bug

#520 Remove loguru catch
  src/kfactory/kcell.py
  src/kfactory/routing/aa/optical.py
  src/kfactory/routing/optical.py
Labels: bug, routing

#521 Fix fill_tiled segfault
  src/kfactory/utils/fill.py
Labels: bug
