Repository gdsfactory/kfactory, pull requests merged in 2024-03, with the labels that each got.

#264 Move @vcell to KCLayout
  src/kfactory/kcell.py
Labels: enhancement

#267 fix KCLayout not allowing constants in the constructor
  src/kfactory/kcell.py
Labels: bug

#268 Fix factories for euler and taper
  src/kfactory/factories/euler.py
  src/kfactory/factories/taper.py
Labels: bug

#269 Fix initialization of KCLayout.constants
  src/kfactory/kcell.py
Labels: bug

#270 Fix KCellEnclosure and rename bbox_per_layer to bbox
  src/kfactory/enclosure.py
  src/kfactory/utils/violations.py
  src/kfactory/widgets/interactive.py
Labels: bug

#275 fix manahattan router terminating routing too early
  src/kfactory/routing/manhattan.py
Labels: bug, routing

#278 Fix proxy KCells
  src/kfactory/__init__.py
  src/kfactory/kcell.py
  tests/test_meta.py
  tests/test_pdk.py
Labels: bug

#280 Implement protocols for routing functions
  src/kfactory/enclosure.py
  src/kfactory/factories/__init__.py
  src/kfactory/routing/electrical.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  src/kfactory/typings.py
Labels: documentation, routing

#282 Add `copy_polar` to `Port`
  src/kfactory/kcell.py
  tests/test_ports.py
Labels: enhancement

#284 Fix routing issues
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  tests/test_routing.py
Labels: bug, enhancement, routing

#285 serialize settings
  pyproject.toml
  src/kfactory/kcell.py
Labels: enhancement

#273 Add post process
  src/kfactory/kcell.py
  tests/test_cell.py
Labels: enhancement
