Repository gdsfactory/kfactory, pull requests merged in 2024-12, with the labels that each got.

#526 fix writer using gdsii always
  .pre-commit-config.yaml
  src/kfactory/factories/bezier.py
  src/kfactory/kcell.py
  tests/test_meta.py
Labels: bug

#530 update pipelines to use uv
  .github/workflows/pages.yml
  .github/workflows/test_code.yml
Labels: github_actions

#531 fix dict serialization
  src/kfactory/kcell.py
Labels: bug

#532 add better handling of placing errors
  src/kfactory/kcell.py
  src/kfactory/routing/electrical.py
  src/kfactory/routing/generic.py
  src/kfactory/routing/optical.py
  tests/test_routing.py
Labels: enhancement, routing

#536 better LockedError message
  .pre-commit-config.yaml
  src/kfactory/kcell.py
Labels: enhancement
