Repository gdsfactory/kfactory, pull requests merged in 2024-07, with the labels that each got.

#418 make OpticalManhattanRoute better
  src/kfactory/routing/optical.py
Labels: enhancement, routing

#419 update klayout and pre-commit
  .pre-commit-config.yaml
  pyproject.toml
Labels: dependencies

#421 Add name debugging config
  src/kfactory/conf.py
  src/kfactory/kcell.py
Labels: enhancement

#426 Fix `KCLayout.read(..., register_cells=True)`
  src/kfactory/kcell.py
Labels: bug

#430 Add InstanceGroup
  src/kfactory/kcell.py
Labels: enhancement

#432 fix error message
  src/kfactory/kcell.py
Labels: bug

#431 add packing functions for Instances and KCells
  pyproject.toml
  src/kfactory/__init__.py
  src/kfactory/kcell.py
  src/kfactory/packing.py
Labels: enhancement

#434 fix add_ports in case port.kcl is not ports.kcl
  .pre-commit-config.yaml
  src/kfactory/kcell.py
Labels: bug, enhancement

#435 fix _port
  src/kfactory/kcell.py
Labels: bug

#438 Adjust AttributeError text in optical routing for taper and bend
  src/kfactory/routing/optical.py
Labels: bug

#441 fix c.flatten(merge=True) deleting texts
  src/kfactory/kcell.py
Labels: bug

#443 ensure cell decorated functions return component
  src/kfactory/kcell.py
Labels: bug
