Repository gdsfactory/kfactory, pull requests merged in 2024-06, with the labels that each got.

#364 typo
  src/kfactory/kcell.py
Labels: bug

#365 fix dy for VInstance
  src/kfactory/kcell.py
Labels: bug

#366 Better error prints
  src/kfactory/kcell.py
Labels: enhancement

#362 Add `overwrite_existing` and `layout_cache` options to the cell decorator
  src/kfactory/conf.py
  src/kfactory/kcell.py
  src/kfactory/utils/fill.py
  tests/conftest.py
  tests/test_cell.py
  tests/test_routing.py
Labels: enhancement

#367 fix locked cell error
  src/kfactory/kcell.py
Labels: bug

#368 Improve logger
  docs/source/config.md
  src/kfactory/__init__.py
  src/kfactory/conf.py
  src/kfactory/enclosure.py
  src/kfactory/factories/circular.py
  src/kfactory/factories/euler.py
  src/kfactory/factories/straight.py
  src/kfactory/factories/taper.py
  src/kfactory/factories/virtual/circular.py
  src/kfactory/factories/virtual/euler.py
  src/kfactory/factories/virtual/straight.py
  src/kfactory/kcell.py
  src/kfactory/routing/aa/optical.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  src/kfactory/utils/fill.py
  src/kfactory/widgets/interactive.py
  tests/test_cells.py
Labels: documentation, enhancement, routing

#374 Improve and fix enclosure_tiled for KCellEnclosure and LayerEnclosure
  src/kfactory/enclosure.py
  src/kfactory/kcell.py
  tests/test_rename.py
Labels: bug

#375 Drop rec_dicts flag and make it default to use rec dict inspection
  .pre-commit-config.yaml
  src/kfactory/kcell.py
  tests/test_cell.py
Labels: breaking

#376 try to fix cicd
  .github/workflows/test_code.yml
Labels: bug, github_actions

#378 add func.__name__ for partials
  src/kfactory/kcell.py
Labels: enhancement

#379 Fix cells duplicated by having settings and info
  src/kfactory/kcell.py
Labels: bug

#380 add to_um and to_dbu into KCLayout
  docs/source/notebooks/00_geometry.py
  docs/source/notebooks/01_references.py
  docs/source/notebooks/02_DRC.py
  docs/source/notebooks/03_Enclosures.py
  docs/source/notebooks/04_KCL.py
  docs/source/notebooks/demo.gds
  src/kfactory/enclosure.py
  src/kfactory/factories/euler.py
  src/kfactory/kcell.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  src/kfactory/utils/fill.py
  src/kfactory/utils/violations.py
  tests/test_cell.py
  tests/test_instance.py
Labels: enhancement, routing

#383 Fix dcplx_trans setter on Port
  pyproject.toml
  src/kfactory/kcell.py
  tests/test_ports.py
Labels: bug

#384 pass flags to connect
  src/kfactory/routing/optical.py
Labels: bug, routing

#385 fix plot with vinsts
  src/kfactory/kcell.py
  src/kfactory/widgets/interactive.py
Labels: bug

#388 fix routing issues with bounding boxes
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  tests/test_smart_routing.py
Labels: bug, routing

#389 Add functional `check_ports` to `@cell` decorators
  src/kfactory/kcell.py
  tests/test_cell.py
Labels: enhancement

#390 fix erroneous start for route_loosely
  src/kfactory/routing/manhattan.py
  tests/test_smart_routing.py
Labels: bug, routing

#393 fix connect when using port objects on self
  src/kfactory/kcell.py
  tests/conftest.py
  tests/test_transformations.py
Labels: bug

#397 fix routing errors and add a better test
  src/kfactory/enclosure.py
  src/kfactory/routing/manhattan.py
  tests/test_routing.py
  tests/test_smart_routing.py
Labels: bug, routing

#396 add display_kcell display_type
  src/kfactory/conf.py
  src/kfactory/kcell.py
  src/kfactory/widgets/interactive.py
Labels: enhancement

#400 fix basename usage in cell decorator
  src/kfactory/kcell.py
Labels: bug

#398 full test suite for smart routing and error fixes
  src/kfactory/kcell.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  tests/conftest.py
  tests/test_routing.py
Labels: bug, routing

#399 works with partials
  src/kfactory/kcell.py
Labels: bug

#402 fix indirect routing
  pyproject.toml
  src/kfactory/routing/manhattan.py
  tests/test_routing.py
Labels: bug, routing

#403 fix connection issue caring about mirror when it should not
  CHANGELOG.md
  src/kfactory/kcell.py
Labels: bug, documentation

#409 Routing indirect fixes
  .github/workflows/test_code.yml
  CHANGELOG.md
  src/kfactory/kcell.py
  src/kfactory/routing/manhattan.py
  tests/test_all_angle.py
  tests/test_cell.py
  tests/test_cells.py
  tests/test_cplxcells.py
  tests/test_enclosure.py
  tests/test_extrude.py
  tests/test_grid.py
  tests/test_instance.py
  tests/test_meta.py
  tests/test_pdk.py
  tests/test_routing.py
  tests/test_transformations.py
  tests/test_virtual.py
Labels: documentation, enhancement, routing

#405 Use tempfile if called from IPython
  src/kfactory/kcell.py
Labels: enhancement

#411 Add check for klayout/klive version vs kfactory
  src/kfactory/kcell.py
Labels: enhancement

#412 fix l2n extraction and add test
  CHANGELOG.md
  src/kfactory/kcell.py
  tests/test_l2n.py
Labels: bug, documentation

#413 fix hierarchy of yaml parser and add test
  src/kfactory/placer.py
  tests/test_yaml.py
Labels: bug

#414 fix kclayout nested cells and ports/metainfo issues
  src/kfactory/kcell.py
  tests/test_l2n.py
Labels: bug

#415 find dotenv
  src/kfactory/conf.py
Labels: bug
