Repository gdsfactory/kfactory, pull requests merged in 2024-10, with the labels that each got.

#483 fix AREF ports
  .pre-commit-config.yaml
  src/kfactory/kcell.py
Labels: bug

#481 Add SymmetricalCrossSection
  .pre-commit-config.yaml
  src/kfactory/conf.py
  src/kfactory/cross_section.py
  src/kfactory/enclosure.py
  src/kfactory/kcell.py
  tests/test_cells.py
  tests/test_meta.py
Labels: enhancement

#489 fix naming of cells from vinsts
  src/kfactory/kcell.py
Labels: bug

#490 fix layerenum
  src/kfactory/kcell.py
Labels: bug

#491 add instance iterator which returns coord plus port
  src/kfactory/kcell.py
Labels: enhancement

#492 Py310 backport
  .github/workflows/test_code.yml
  pyproject.toml
  src/kfactory/cli/build.py
  src/kfactory/conf.py
  src/kfactory/cross_section.py
  src/kfactory/enclosure.py
  src/kfactory/kcell.py
Labels: bug, github_actions

#495 add transform_ports option to KCell.transform
  src/kfactory/grid.py
  src/kfactory/kcell.py
Labels: enhancement

#493 Add Router start/end straight steps
  src/kfactory/routing/electrical.py
  src/kfactory/routing/generic.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  src/kfactory/routing/steps.py
  tests/test_routing.py
Labels: enhancement, routing

#496 add tag support for cell decorator
  src/kfactory/kcell.py
Labels: enhancement

#497 add saveoptions to build cli
  src/kfactory/cli/build.py
Labels: enhancement

#498 add port reorientation for route_bundle
  src/kfactory/routing/electrical.py
  src/kfactory/routing/generic.py
  src/kfactory/routing/optical.py
  tests/test_routing.py
Labels: enhancement, routing

#499 fix typo
  src/kfactory/routing/optical.py
Labels: bug, routing

#502 add length and length_straight to electrical routes
  src/kfactory/routing/electrical.py
Labels: enhancement, routing

#501 make add_ports agnostic to kcl
  src/kfactory/kcell.py
Labels: enhancement

#503 fix missing arg
  src/kfactory/kcell.py
Labels: bug

#504 add suffix
  src/kfactory/kcell.py
Labels: enhancement

#505 fix error in width calculation of waypoints
  src/kfactory/routing/manhattan.py
Labels: bug, routing
