Repository gdsfactory/kfactory, pull requests merged in 2024-05, with the labels that each got.

#304 add minimum_straight
  src/kfactory/routing/electrical.py
Labels: enhancement, routing

#307 allow_different_port_widths for electrical routing
  src/kfactory/routing/optical.py
Labels: enhancement, routing

#305 Improve VKCell/VInstance
  src/kfactory/factories/euler.py
  src/kfactory/kcell.py
  src/kfactory/kcell.py.orig
  src/kfactory/routing/aa/optical.py
  tests/test_all_angle.py
  tests/test_meta.py.orig
Labels: enhancement, routing

#309 Fix route_smart ignoring bounding boxes at the end of the routes
  src/kfactory/routing/manhattan.py
  tests/test_smart_routing.py
Labels: bug, routing

#306 `pprint_ports` add missing type switch
  src/kfactory/kcell.py
Labels: bug

#310 fix grid instance array not properly setting up the array
  src/kfactory/grid.py
Labels: bug

#314 Improve fill tiled with row/column vectors
  src/kfactory/kcell.py
  src/kfactory/utils/fill.py
  tests/conftest.py
  tests/test_fill.py
Labels: enhancement

#316 ports in instance
  src/kfactory/kcell.py
  tests/test_cell.py
Labels: bug

#317 add instance.size_info
  src/kfactory/kcell.py
  tests/test_cell.py
Labels: enhancement

#319 rename allow_width_mismatch
  src/kfactory/routing/optical.py
Labels: documentation

#323 add write configs and connection behavior
  src/kfactory/conf.py
  src/kfactory/kcell.py
  src/kfactory/routing/optical.py
Labels: enhancement, routing

#324 add clear_kcells
  src/kfactory/kcell.py
Labels: enhancement

#325 allow new conf fields
  src/kfactory/conf.py
Labels: enhancement

#326 fix add port
  src/kfactory/kcell.py
Labels: bug

#331 Separate function name
  src/kfactory/kcell.py
  tests/test_meta.py
Labels: enhancement

#332 Add global flags for connection to not carry over rotation or angle
  src/kfactory/conf.py
  src/kfactory/kcell.py
Labels: enhancement

#334 Fix all angle bundle router
  src/kfactory/routing/aa/optical.py
  tests/_test_meta_sample.oas
  tests/test_all_angle.py
  tests/test_virtual.py
Labels: bug, routing

#335 Add `route_smart` and `route_bundle` port sort
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  tests/test_smart_routing.py
Labels: enhancement, routing

#336 Fix route_bundle requiring a non-empty list of bounding boxes
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
Labels: bug, routing

#337 Fix single bundle case for route_bundle
  src/kfactory/routing/manhattan.py
Labels: bug, routing

#338 Fix metaformat
  src/kfactory/kcell.py
Labels: bug

#339 Change to `d{key}` instead of `d.{key}`
  .pre-commit-config.yaml
  README.md
  docs/source/gdsfactory.md
  docs/source/notebooks/00_geometry.py
  docs/source/notebooks/03_Enclosures.py
  docs/source/notebooks/04_KCL.py
  pyproject.toml
  src/kfactory/__init__.py
  src/kfactory/kcell.py
  src/kfactory/routing/aa/optical.py
  tests/test_cell.py
  tests/test_instance.py
  tests/test_transformations.py
Labels: documentation, github_actions, breaking, routing

#340 add center to SizeInfo
  src/kfactory/kcell.py
Labels: enhancement

#341 Add enum for handling check_instances
  src/kfactory/conf.py
  src/kfactory/kcell.py
Labels: enhancement

#342 add route_width to `optical.route`
  src/kfactory/routing/optical.py
Labels: enhancement, routing

#343 fix basename and function_name metainfo
  src/kfactory/kcell.py
Labels: bug

#344 Add `multi` option to fill and fix bugs
  src/kfactory/utils/fill.py
Labels: bug, enhancement

#345 fix global config settings only being set on first import
  src/kfactory/kcell.py
  src/kfactory/routing/optical.py
  src/kfactory/utils/fill.py
Labels: bug, routing

#350 `mirror` and `dmirror` M90 by default
  src/kfactory/kcell.py
Labels: enhancement, breaking

#349 Improve drotate
  src/kfactory/kcell.py
Labels: bug

#346 Add hash to long automatic cell name
  src/kfactory/kcell.py
Labels: enhancement

#351 fix typo
  src/kfactory/kcell.py
Labels: bug

#353 Improve all-angle route_bundle to allow no backbone
  src/kfactory/kcell.py
  src/kfactory/routing/aa/optical.py
  tests/test_all_angle.py
Labels: enhancement, routing

#355 Fix VKCell Setting Units
  src/kfactory/kcell.py
  tests/test_smart_routing.py
Labels: bug

#358 fix virtual cell show hierarchy error
  src/kfactory/kcell.py
Labels: bug

#359 Add lyrdb option to `plot`
  .pre-commit-config.yaml
  src/kfactory/kcell.py
  src/kfactory/routing/aa/optical.py
  src/kfactory/routing/optical.py
  src/kfactory/widgets/interactive.py
Labels: enhancement, routing

#360 Add all easy access properties to VKCell and VInstance
  src/kfactory/kcell.py
Labels: enhancement
