Repository gdsfactory/kfactory, pull requests merged in 2024-09, with the labels that each got.

#462 fix errors for `kf run` not finding modules. Change syntax
  src/kfactory/cli/__init__.py
  src/kfactory/cli/build.py
  src/kfactory/cli/runshow.py
Labels: bug

#463 fix generic route not passing routing width to placer_function
  src/kfactory/routing/electrical.py
  src/kfactory/routing/generic.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  tests/test_routing.py
Labels: bug, routing

#465 Fix meta
  pyproject.toml
  src/kfactory/kcell.py
  tests/test_pdk.py
Labels: bug

#466 fix add_port using arg call instead of kwarg call
  src/kfactory/kcell.py
Labels: bug

#469 fix apply_bbox for LayerInfo objects
  MERGE_READ.oas
  src/kfactory/enclosure.py
  tests/test_enclosure.py
Labels: bug

#470 fix layout-cache not honoring overwrite-existing
  src/kfactory/kcell.py
Labels: bug

#471 Better build cli
  src/kfactory/cli/build.py
Labels: enhancement

#473 add waypoint routing
  .pre-commit-config.yaml
  MERGE_READ.oas
  pyproject.toml
  src/kfactory/routing/electrical.py
  src/kfactory/routing/generic.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  tests/test_routing.py
Labels: enhancement, routing

#476 readd LayerEnum to be available as kf.LayerEnum
  src/kfactory/__init__.py
Labels: bug

#477 Fix read for layout meta merge
  .github/workflows/test_code.yml
  CHANGELOG.md
  src/kfactory/kcell.py
Labels: bug, documentation, github_actions

#478 bump klayout to 0.29.7
  pyproject.toml
Labels: dependencies

#480 decrease log level of layout_cache and klayout version mismatch log messages
  src/kfactory/conf.py
  src/kfactory/kcell.py
Labels: bug
