Repository gdsfactory/kfactory, pull requests merged in 2024-08, with the labels that each got.

#447 Add missing space in KLayout version warning
  src/kfactory/kcell.py
Labels: bug

#448 fix write_context_info
  src/kfactory/kcell.py
Labels: bug, help wanted

#450 better instance default name using trans instead of .x
  src/kfactory/kcell.py
Labels: bug

#439 Improve layers so that they can be passed easily by LayerInfo and not only by index
  .gitignore
  docs/source/complex_cell.py
  docs/source/layers.py
  docs/source/notebooks/00_geometry.py
  docs/source/notebooks/01_references.py
  docs/source/notebooks/02_DRC.py
  docs/source/notebooks/03_Enclosures.py
  docs/source/notebooks/04_KCL.py
  docs/source/star.py
  docs/source/straight.py
  src/kfactory/__init__.py
  src/kfactory/cells/straight.py
  src/kfactory/cells/taper.py
  src/kfactory/conf.py
  src/kfactory/enclosure.py
  src/kfactory/factories/bezier.py
  src/kfactory/factories/circular.py
  src/kfactory/factories/euler.py
  src/kfactory/factories/straight.py
  src/kfactory/factories/taper.py
  src/kfactory/factories/virtual/circular.py
  src/kfactory/factories/virtual/euler.py
  src/kfactory/factories/virtual/straight.py
  src/kfactory/factories/virtual/utils.py
  src/kfactory/kcell.py
  src/kfactory/kf_types.py
  src/kfactory/utils/fill.py
  src/kfactory/utils/violations.py
  tests/conftest.py
  tests/test_all_angle.py
  tests/test_cell.py
  tests/test_cells.py
  tests/test_cplxcells.py
  tests/test_enclosure.py
  tests/test_extrude.py
  tests/test_fill.py
  tests/test_instance.py
  tests/test_l2n.py
  tests/test_layerstack.py
  tests/test_meta.py
  tests/test_netlist.py
  tests/test_partial.py
  tests/test_pdk.py
  tests/test_ports.py
  tests/test_rename.py
  tests/test_routing.py
  tests/test_shapes.py
  tests/test_spiral.py
  tests/test_transformations.py
  tests/test_violations.py
  tests/test_virtual.py
  tests/test_yaml.py
Labels: enhancement, cells, breaking

#453 fix load_layout_options
  src/kfactory/kcell.py
Labels: bug

#451 add initial implementation for decorators
  .github/workflows/test_code.yml
  .pre-commit-config.yaml
  pyproject.toml
  src/kfactory/decorators.py
  src/kfactory/kcell.py
  src/kfactory/kf_types.py
Labels: enhancement, github_actions

#454 fix #452
  src/kfactory/kcell.py
Labels: bug

#460 fix errors in enclosures and relax some port layer constraints
  src/kfactory/enclosure.py
  src/kfactory/kcell.py
Labels: bug

#456 clean up route_bundle
  .github/workflows/pages.yml
  .github/workflows/release.yml
  .github/workflows/test_code.yml
  pyproject.toml
  src/kfactory/routing/__init__.py
  src/kfactory/routing/electrical.py
  src/kfactory/routing/generic.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  tests/conftest.py
  tests/test_netlist.py
  tests/test_routing.py
Labels: enhancement, github_actions, routing

#461 add config option for custom show functions
  .pre-commit-config.yaml
  docs/source/config.md
  src/kfactory/conf.py
  src/kfactory/kcell.py
  tests/custom/show.py
  tests/test_config.py
Labels: documentation, enhancement
