Repository gdsfactory/kfactory, pull requests merged in 2025-01, with the labels that each got.

#538 Add lockfile and more commands to makefile
  Makefile
  pyproject.toml
  uv.lock
Labels: dependencies, cicd

#528 Add BaseKCell class and update VKCell and KCell to inherit from it
  src/kfactory/__init__.py
  src/kfactory/grid.py
  src/kfactory/kcell.py
  src/kfactory/placer.py
Labels: enhancement

#541 fix port
  src/kfactory/kcell.py
  tests/test_instance.py
Labels: bug, enhancement

#544 Easier mirror
  src/kfactory/kcell.py
  tests/test_instance.py
Labels: enhancement

#545 Add BaseKCell to __init__.py
  src/kfactory/__init__.py
Labels: enhancement

#547 fix VInstance.bbox and duplication of VKCell
  src/kfactory/kcell.py
Labels: bug

#549 Add more locked checks to VKCell and remade lock file
  src/kfactory/kcell.py
  uv.lock
Labels: enhancement

#555 fix virtual write #550
  .pre-commit-config.yaml
  src/kfactory/kcell.py
  tests/test_virtual.py
Labels: bug

#556 fix #525
  src/kfactory/kcell.py
Labels: bug

#557 update tests
  pyproject.toml
  src/kfactory/factories/virtual/euler.py
  src/kfactory/factories/virtual/straight.py
  src/kfactory/kcell.py
  src/kfactory/placer.py
  src/kfactory/routing/aa/optical.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  src/kfactory/widgets/interactive.py
  tests/test_all_angle.py
  tests/test_cell.py
  tests/test_cells.py
  tests/test_config.py
  tests/test_enclosure.py
  tests/test_l2n.py
  tests/test_meta.py
  tests/test_netlist.py
  tests/test_ports.py
  tests/test_routing.py
  tests/test_spiral.py
  tests/test_transformations.py
  tests/test_virtual.py
  uv.lock
Labels: routing

#559 Fix more tests
  .github/workflows/test_code.yml
  Makefile
  README.md
  docs/source/notebooks/00_geometry.py
  docs/source/notebooks/02_DRC.py
  pyproject.toml
  src/kfactory/factories/circular.py
  src/kfactory/factories/euler.py
  src/kfactory/factories/virtual/circular.py
  src/kfactory/factories/virtual/euler.py
  src/kfactory/factories/virtual/straight.py
  src/kfactory/kcell.py
  src/kfactory/placer.py
  src/kfactory/routing/aa/optical.py
  tests/test_all_angle.py
  tests/test_cell.py
  tests/test_cplxcells.py
  tests/test_ports.py
  tests/test_spiral.py
  uv.lock
Labels: bug, documentation, github_actions, routing

#562 Dkcell tests
  .gitignore
  .pre-commit-config.yaml
  MERGE_READ.oas
  pyproject.toml
  src/kfactory/__init__.py
  src/kfactory/cli/build.py
  src/kfactory/conf.py
  src/kfactory/decorators.py
  src/kfactory/enclosure.py
  src/kfactory/factories/__init__.py
  src/kfactory/factories/circular.py
  src/kfactory/factories/euler.py
  src/kfactory/factories/straight.py
  src/kfactory/kcell.py
  src/kfactory/placer.py
  src/kfactory/port.py
  src/kfactory/routing/__init__.py
  src/kfactory/routing/electrical.py
  src/kfactory/routing/generic.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  src/kfactory/routing/steps.py
  src/kfactory/utils/__init__.py
  src/kfactory/utils/violations.py
  tests/conftest.py
  tests/custom/show.py
  tests/test_all_angle.py
  tests/test_cell.py
  tests/test_cells.py
  tests/test_config.py
  tests/test_cplxcells.py
  tests/test_dkcell.py
  tests/test_enclosure.py
  tests/test_extrude.py
  tests/test_fill.py
  tests/test_grid.py
  tests/test_instance.py
  tests/test_l2n.py
  tests/test_layerstack.py
  tests/test_meta.py
  tests/test_netlist.py
  tests/test_partial.py
  tests/test_pdk.py
  tests/test_ports.py
  tests/test_rename.py
  tests/test_routing.py
  tests/test_shapes.py
  tests/test_spiral.py
  tests/test_transformations.py
  tests/test_violations.py
  tests/test_virtual.py
  tests/test_yaml.py
  uv.lock
Labels: documentation, github_actions, routing

#564 Remove insts from TKCell
  MERGE_READ.oas
  src/kfactory/kcell.py
  tests/test_all_angle.py
  tests/test_dkcell.py
Labels: enhancement

#568 Setup codecov
  .github/workflows/test_code.yml
  Makefile
  README.md
Labels: documentation, github_actions

#569 Add converage config
  .coveragerc
Labels: enhancement

#570 Fix instance collision error
  src/kfactory/kcell.py
Labels: bug, documentation

#572 Make all arguments for add_port and add_ports kw
  docs/source/notebooks/00_geometry.py
  src/kfactory/kcell.py
  tests/test_cell.py
  tests/test_cplxcells.py
  tests/test_l2n.py
  tests/test_netlist.py
  tests/test_pdk.py
  tests/test_ports.py
  tests/test_routing.py
  tests/test_spiral.py
  uv.lock
Labels: enhancement

#573 Use kdb.Cell.locked/is_locked for KCell locking
  src/kfactory/MERGE_READ.oas
  src/kfactory/kcell.py
  tests/test_cell.py
  tests/test_dkcell.py
  tests/test_meta.py
Labels: enhancement

#575 Add inheritance for bounding box operations
  .pre-commit-config.yaml
  src/kfactory/grid.py
  src/kfactory/kcell.py
  src/kfactory/routing/generic.py
  tests/test_instance.py
  tests/test_instance_group.py
  tests/test_transformations.py
Labels: enhancement, routing

#576 Fix cell decorator
  docs/mkdocs.yml
  docs/source/notebooks/00_geometry.py
  docs/source/pcells.md
  src/kfactory/__init__.py
  src/kfactory/decorators.py
  src/kfactory/factories/bezier.py
  src/kfactory/factories/circular.py
  src/kfactory/factories/euler.py
  src/kfactory/factories/straight.py
  src/kfactory/factories/taper.py
  src/kfactory/kcell.py
  tests/test_cell.py
  tests/test_routing.py
Labels: bug, documentation

#579 Fix locking logic
  src/kfactory/kcell.py
  tests/conftest.py
  tests/test_cell.py
  tests/test_cells.py
  tests/test_data/ref/taper.gds
  tests/test_data/ref/taper_W500_W1000_L10000_LWG_EWGSTD.gds
Labels: bug

#578 add some basic thread safety locks
  src/kfactory/kcell.py
  tests/conftest.py
  tests/test_cell.py
  tests/test_cells.py
  tests/test_data/ref/taper.gds
  tests/test_data/ref/taper_W500_W1000_L10000_LWG_EWGSTD.gds
  tests/test_routing.py
Labels: enhancement

#571 Add more tests
  .github/workflows/test_code.yml
  .pre-commit-config.yaml
  Makefile
  pyproject.toml
  src/kfactory/cli/__init__.py
  src/kfactory/kcell.py
  tests/cli/__init__.py
  tests/cli/test_cli.py
  tests/conftest.py
  tests/test_cell.py
  tests/test_cells.py
  tests/test_config.py
  tests/test_data/ref/taper.gds
  tests/test_data/ref/taper_W500_W1000_L10000_LWG_EWGSTD.gds
  tests/test_dkcell.py
  tests/test_enclosure.py
  tests/test_layers.py
  tests/test_layout.py
  tests/test_meta.py
  tests/test_pdk.py
  tests/test_ports.py
  tests/test_routing.py
  tests/test_settings.py
  tests/test_utilities.py
  tests/test_virtual.py
  uv.lock
Labels: enhancement, github_actions

#581 Harmonize KCell.transform
  src/kfactory/kcell.py
Labels: enhancement

#582 Add RUF rule to ruff and rearanged added
  pyproject.toml
  src/kfactory/__init__.py
  src/kfactory/cells/__init__.py
  src/kfactory/enclosure.py
  src/kfactory/kcell.py
  src/kfactory/port.py
  src/kfactory/routing/optical.py
Labels: enhancement, cells, routing

#584 Cast protoport to port before int angle match
  src/kfactory/port.py
Labels: bug

#585 Add instances contains
  src/kfactory/instances.py
  tests/test_instances.py
Labels: enhancement

#586 Fix um grid
  src/kfactory/grid.py
  src/kfactory/kcell.py
  tests/test_grid.py
  uv.lock
Labels: bug

#588 Add defaults for mirror, mirror_x, mirror_y
  src/kfactory/geometry.py
  tests/test_instance.py
Labels: enhancement

#587 Make vinstance connect take ProtoPort
  src/kfactory/exceptions.py
  src/kfactory/instance.py
  tests/test_instance.py
Labels: bug, enhancement

#589 Add to_itype, to_dtype to dbu, um classes
  src/kfactory/instance.py
  src/kfactory/instance_group.py
  src/kfactory/instances.py
  src/kfactory/kcell.py
  src/kfactory/layout.py
  src/kfactory/port.py
  src/kfactory/ports.py
  src/kfactory/routing/electrical.py
  src/kfactory/routing/generic.py
  tests/test_cell.py
  tests/test_grid.py
  tests/test_instance.py
  tests/test_instance_group.py
  tests/test_instances.py
  tests/test_ports.py
Labels: enhancement, routing

#592 Add ruff bugbear rule
  pyproject.toml
  src/kfactory/conf.py
  src/kfactory/enclosure.py
  src/kfactory/factories/bezier.py
  src/kfactory/grid.py
  src/kfactory/instance.py
  src/kfactory/kcell.py
  src/kfactory/layer.py
  src/kfactory/layout.py
  src/kfactory/merge.py
  src/kfactory/packing.py
  src/kfactory/port.py
  src/kfactory/ports.py
  src/kfactory/routing/aa/optical.py
  src/kfactory/routing/electrical.py
  src/kfactory/routing/generic.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  src/kfactory/routing/steps.py
  src/kfactory/serialization.py
  src/kfactory/utils/fill.py
  tests/test_config.py
  tests/test_enclosure.py
  tests/test_instance_group.py
  tests/test_pdk.py
  tests/test_rename.py
Labels: enhancement, routing

#591 Add ruff Naming rule and fix most errors
  pyproject.toml
  src/kfactory/conf.py
  src/kfactory/decorators.py
  src/kfactory/enclosure.py
  src/kfactory/exceptions.py
  src/kfactory/factories/euler.py
  src/kfactory/instance.py
  src/kfactory/kcell.py
  src/kfactory/layout.py
  src/kfactory/port.py
  src/kfactory/routing/electrical.py
  src/kfactory/settings.py
  src/kfactory/technology/layer_map.py
  tests/conftest.py
  tests/test_all_angle.py
  tests/test_cell.py
  tests/test_cells.py
  tests/test_cplxcells.py
  tests/test_enclosure.py
  tests/test_extrude.py
  tests/test_fill.py
  tests/test_instance.py
  tests/test_instance_ports.py
  tests/test_instances.py
  tests/test_layers.py
  tests/test_layerstack.py
  tests/test_layout.py
  tests/test_meta.py
  tests/test_netlist.py
  tests/test_partial.py
  tests/test_pdk.py
  tests/test_ports.py
  tests/test_rename.py
  tests/test_routing.py
  tests/test_shapes.py
  tests/test_spiral.py
  tests/test_transformations.py
  tests/test_violations.py
  tests/test_virtual.py
Labels: enhancement, routing

#595 Add ports tests
  Makefile
  src/kfactory/cross_section.py
  src/kfactory/enclosure.py
  src/kfactory/instance_ports.py
  src/kfactory/instances.py
  src/kfactory/kcell.py
  src/kfactory/layer.py
  src/kfactory/layout.py
  src/kfactory/port.py
  src/kfactory/ports.py
  src/kfactory/settings.py
  src/kfactory/typings.py
  tests/test_cell.py
  tests/test_cells.py
  tests/test_dkcell.py
  tests/test_instance_ports.py
  tests/test_layers.py
  tests/test_packing.py
  tests/test_port.py
  tests/test_ports.py
Labels: enhancement
