Repository gdsfactory/kfactory, pull requests merged in 2025-03, with the labels that each got.

#631 Fix optical place90 and BasePort.transformed docstring
  src/kfactory/port.py
  src/kfactory/routing/optical.py
  uv.lock
Labels: bug, routing

#632 fix connectivity checks
  src/kfactory/utilities.py
Labels: bug

#635 pin klayout version
  .pre-commit-config.yaml
  pyproject.toml
Labels: bug, dependencies

#637 add error messages for name conflicts on renaming
  .pre-commit-config.yaml
  src/kfactory/kcell.py
  src/kfactory/layout.py
Labels: enhancement

#638 fix connectivity-check
  src/kfactory/kcell.py
Labels: bug

#640 Test connectivity
  .pre-commit-config.yaml
  pyproject.toml
  src/kfactory/factories/euler.py
  src/kfactory/grid.py
  src/kfactory/instance_ports.py
  src/kfactory/kcell.py
  src/kfactory/port.py
  src/kfactory/routing/electrical.py
  src/kfactory/routing/generic.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  tests/test_connectivity.py
  tests/test_data/nxn_chiplets.gds
Labels: bug, routing

#641 make cell test more versatile
  tests/test_cells.py
  tests/test_data/ref/bend_circular_W1_R10_LWG_EWGSTD_A180_AS1.gds
  tests/test_data/ref/bend_circular_W1_R10_LWG_EWGSTD_A90_AS1.gds
  tests/test_data/ref/bend_euler_W1_R10_LWG_EWGSTD_A180_R150.gds
  tests/test_data/ref/bend_euler_W1_R10_LWG_EWGSTD_A30_R150.gds
  tests/test_data/ref/bend_euler_W1_R10_LWG_EWGSTD_A90_R150.gds
  tests/test_data/ref/bend_s_bezier_W1_H10_L100_LWG_NP99_TS0_TS1_EWGSTD.gds
  tests/test_data/ref/bend_s_euler_O10_W1_R30_LWG_EWGSTD_R150.gds
  tests/test_data/ref/fill_cell.gds
  tests/test_data/ref/straight_W1000_L100000_LWG_EWGSTD.gds
  tests/test_data/ref/straight_W500_L1000_LWG_EWGSTD.gds
  tests/test_data/ref/taper_W1000_W10000_L50000_LWG_EWGSTD.gds
  tests/test_data/ref/taper_W500_W1000_L10000_LWG_EWGSTD.gds
  tests/test_data/ref/virtual_bend_circular_W1_R10_LWG_EWGSTD_A30_AS1.gds
  tests/test_data/ref/virtual_straight_W0p006_L100p0052_LWG_EWGSTD.gds
  tests/test_ports.py
Labels: github_actions

#643 Add more tests
  .coveragerc
  pyproject.toml
  src/kfactory/instance_ports.py
  src/kfactory/kcell.py
  src/kfactory/port.py
  src/kfactory/utilities.py
  src/kfactory/utils/__init__.py
  tests/test_cell.py
  tests/test_dkcell.py
  tests/test_instance_group.py
  tests/test_instance_ports.py
  tests/test_port.py
  tests/test_ports.py
  tests/test_simplify.py
  tests/test_utilities.py
  uv.lock
Labels: enhancement

#644 fix naming conflicts that are none
  src/kfactory/kcell.py
  src/kfactory/layout.py
Labels: bug

#642 More test coverage
  src/kfactory/__init__.py
  tests/test_cell.py
  tests/test_factories.py
  tests/test_ports.py
Labels: github_actions

#629 make length attribute in ManhattanRoute configurable with length_function
  src/kfactory/__init__.py
  src/kfactory/routing/electrical.py
  src/kfactory/routing/generic.py
  src/kfactory/routing/length_functions.py
  src/kfactory/routing/optical.py
  tests/test_routing.py
Labels: enhancement, routing

#646 Fix pydantic 2.11
  pyproject.toml
  src/kfactory/layer.py
  src/kfactory/layout.py
  uv.lock
Labels: bug

#647 minimum requirements test
  .github/workflows/test_code.yml
  .gitignore
  Makefile
  minimal-reqs.txt
  pyproject.toml
  uv.lock
Labels: enhancement, github_actions

#648 Add Test scheduled workflow
  .github/workflows/schedule.yml
Labels: enhancement, github_actions

#653 Add github token to schedule workflow
  .github/workflows/schedule.yml
Labels: bug, enhancement, github_actions

#654 Remove schedule workflow and add cron to test-code
  .github/workflows/schedule.yml
  .github/workflows/test_code.yml
Labels: github_actions

#655 Update min req test
  Makefile
  minimal-reqs.txt
  pyproject.toml
  uv.lock
Labels: bug

#656 Remove klayout api from docs
  docs/mkdocs.yml
  docs/source/gen_ref_pages.py
Labels: bug

#657 add some extensions to griffe and mkdocs
  Makefile
  docs/mkdocs.yml
  pyproject.toml
Labels: enhancement

#660 Fix decorator
  src/kfactory/layout.py
Labels: bug
