Repository gdsfactory/kfactory, pull requests merged in 2025-02, with the labels that each got.

#597 Add concrete iter for InstancePorts and DInstancePorts
  src/kfactory/instance_ports.py
  tests/test_instance_ports.py
Labels: enhancement

#598 Add more concrete methods for Instances
  src/kfactory/instance.py
  src/kfactory/instance_group.py
  src/kfactory/kcell.py
  src/kfactory/protocols.py
Labels: enhancement

#596 Rework cross section
  src/kfactory/__init__.py
  src/kfactory/cross_section.py
  src/kfactory/enclosure.py
  src/kfactory/kcell.py
  src/kfactory/layout.py
  src/kfactory/port.py
  src/kfactory/ports.py
  src/kfactory/serialization.py
  tests/test_cross_section.py
  tests/test_meta.py
  tests/test_port.py
Labels: enhancement

#599 Update base_kcell to base and add locked setters
  src/kfactory/kcell.py
  src/kfactory/layout.py
  src/kfactory/ports.py
  tests/test_cell.py
  tests/test_dkcell.py
  tests/test_layout.py
  tests/test_meta.py
  uv.lock
Labels: enhancement

#600 Fix mirror default parameters
  src/kfactory/geometry.py
Labels: bug

#601 Add default args for DPort center and orientation
  src/kfactory/port.py
  tests/test_port.py
Labels: enhancement

#602 Fix KCLayout.clear_kcells
  src/kfactory/layout.py
  tests/test_layout.py
Labels: bug

#603 Fix clear kcells
  src/kfactory/layout.py
  tests/test_layout.py
Labels: bug

#606 Try to fix dependency
  tests/conftest.py
  tests/test_cell.py
  tests/test_cross_section.py
  tests/test_instance_ports.py
  tests/test_port.py
  tests/test_ports.py
Labels: github_actions

#605 Fix electrical route bundle
  src/kfactory/cross_section.py
  src/kfactory/enclosure.py
  src/kfactory/kcell.py
  src/kfactory/routing/electrical.py
  src/kfactory/routing/optical.py
Labels: bug, routing

#608 Fix route_bundle and DPort.copy_polar
  src/kfactory/port.py
  src/kfactory/routing/optical.py
  tests/test_port.py
Labels: bug, routing

#609 fix constructors for kcell/dkcell
  src/kfactory/kcell.py
Labels: bug

#610 better DPort constructor and name optional arg
  src/kfactory/port.py
Labels: bug

#611 fix setter for kcl, there should be no setter
  src/kfactory/geometry.py
  src/kfactory/kcell.py
Labels: bug

#612 fix route bundle waypoints for um interface
  src/kfactory/enclosure.py
  src/kfactory/routing/generic.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  src/kfactory/utils/__init__.py
  tests/test_routing.py
Labels: bug, routing

#613 fix layer naming in LayerInfos
  src/kfactory/layer.py
  tests/test_layers.py
Labels: bug

#614 Fix route width
  src/kfactory/routing/generic.py
  src/kfactory/routing/optical.py
  tests/conftest.py
  tests/test_routing.py
Labels: bug, routing

#616 Fallback for not annotated functions
  src/kfactory/decorators.py
  src/kfactory/instance.py
  src/kfactory/layout.py
  src/kfactory/routing/steps.py
  tests/test_cell.py
Labels: bug, routing

#617 fix waypoints in electrical routing for DKCell
  src/kfactory/routing/electrical.py
Labels: bug, routing

#618 fix dual rail route
  src/kfactory/routing/electrical.py
Labels: bug, routing

#620 Update KCLayout.rebuild to add kcells from the layout
  src/kfactory/layout.py
  tests/test_layout.py
  uv.lock
Labels: enhancement

#624 Fix layer properties conversion
  src/kfactory/technology/layer_map.py
Labels: bug

#625 add a function for `get_component`
  src/kfactory/layout.py
  src/kfactory/typings.py
  tests/test_layout.py
Labels: enhancement

#626 fix duplicate cell because of test
  .pre-commit-config.yaml
  tests/test_layout.py
  uv.lock
Labels: bug

#627 fix the filling functions not accepting all kinds of ProtoTKCell
  src/kfactory/__init__.py
  src/kfactory/utils/fill.py
  src/kfactory/utils/violations.py
Labels: bug

#628 fix library/pdk cells sometimes not getting ports on creation
  src/kfactory/kcell.py
Labels: bug
