Repository gdsfactory/kfactory, pull requests merged in 2025-08, with the labels that each got.

#748 Ability to get a slice of ports
  pyproject.toml
  src/kfactory/ports.py
  tests/test_ports.py
  uv.lock
Labels: enhancement

#747 port difftest from gdsfactory
  src/kfactory/utils/__init__.py
  src/kfactory/utils/difftest.py
  uv.lock
Labels: enhancement

#750 fixes difftest
  src/kfactory/utils/difftest.py
Labels: bug

#755 only pass parameters to show if they are not none
  src/kfactory/kcell.py
Labels: bug

#757 remove find_layer from standard kfactory cells and utils
  src/kfactory/factories/bezier.py
  src/kfactory/factories/circular.py
  src/kfactory/factories/euler.py
  src/kfactory/factories/straight.py
  src/kfactory/factories/taper.py
  src/kfactory/factories/virtual/circular.py
  src/kfactory/factories/virtual/euler.py
  src/kfactory/factories/virtual/straight.py
  src/kfactory/factories/virtual/utils.py
  src/kfactory/port.py
  src/kfactory/utils/difftest.py
  src/kfactory/utils/violations.py
Labels: bug

#758 fix port.layer not returning enum when available
  .github/workflows/test_code.yml
  pyproject.toml
  src/kfactory/port.py
  uv.lock
Labels: bug, github_actions

#759 catch errors if wrong class is returned
  .pre-commit-config.yaml
  src/kfactory/decorators.py
  tests/test_cell.py
Labels: bug, refactor

#760 fix netlist kcl factories retrieval
  src/kfactory/kcell.py
  tests/test_schema.py
Labels: bug

#764 add mirror to SchemaInstance connect
  src/kfactory/layer.py
  src/kfactory/schema.py
  tests/test_schema.py
Labels: enhancement

#771 Remove `if __name__ == '__main__'` in test files
  tests/cli/test_cli.py
  tests/test_dkcell.py
  tests/test_instance.py
  tests/test_instance_group.py
  tests/test_instance_ports.py
  tests/test_instances.py
  tests/test_layers.py
  tests/test_layout.py
  tests/test_meta.py
  tests/test_packing.py
  tests/test_pdk.py
  tests/test_port.py
  tests/test_ports.py
  tests/test_settings.py
  tests/test_simplify.py
  tests/test_utilities.py
  tests/test_vkcell.py
Labels: internal

#773 Use Justfile instead of Makefile
  .github/workflows/pages.yml
  .github/workflows/test_code.yml
  .pre-commit-config.yaml
  Justfile
  Makefile
Labels: github_actions
