Repository gdsfactory/kfactory, pull requests merged in 2025-05, with the labels that each got.

#693 fix layer selection for electrical router
  src/kfactory/routing/electrical.py
Labels: bug, routing

#695 Rename red_knot to ty
  .github/workflows/test_code.yml
Labels: bug, github_actions

#696 Update Ty action
  .github/workflows/test_code.yml
  pyproject.toml
  uv.lock
Labels: github_actions

#697 fix bezier factory out port
  src/kfactory/factories/bezier.py
Labels: bug

#699 fix python versions in make test
  .github/workflows/test_code.yml
  Makefile
Labels: bug, github_actions

#702 Small ty fixes
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  src/kfactory/__init__.py
  src/kfactory/settings.py
  tests/test_settings.py
  tests/test_spiral.py
Labels: github_actions, typing

#700 Add correct conftest import in test files
  tests/__init__.py
  tests/test_all_angle.py
  tests/test_cell.py
  tests/test_cells.py
  tests/test_config.py
  tests/test_cplxcells.py
  tests/test_dkcell.py
  tests/test_enclosure.py
  tests/test_extrude.py
  tests/test_fill.py
  tests/test_instance.py
  tests/test_instance_ports.py
  tests/test_instances.py
  tests/test_l2n.py
  tests/test_layers.py
  tests/test_layerstack.py
  tests/test_layout.py
  tests/test_meta.py
  tests/test_netlist.py
  tests/test_partial.py
  tests/test_pdk.py
  tests/test_port.py
  tests/test_ports.py
  tests/test_rename.py
  tests/test_routing.py
  tests/test_session.py
  tests/test_shapes.py
  tests/test_spiral.py
  tests/test_transformations.py
  tests/test_utilities.py
  tests/test_violations.py
  tests/test_virtual.py
  tests/test_yaml.py
Labels: enhancement, typing

#701 Add conf, kcell to kf exports
  src/kfactory/__init__.py
Labels: enhancement, typing

#704 fix port width errors
  src/kfactory/cross_section.py
  src/kfactory/instance_group.py
  src/kfactory/kcell.py
  src/kfactory/layout.py
  src/kfactory/ports.py
  src/kfactory/protocols.py
  tests/test_cell.py
  tests/test_cross_section.py
  tests/test_port.py
  tests/test_ports.py
Labels: bug

#703 Enhance create_port to have a unified interface
  src/kfactory/cross_section.py
  src/kfactory/instance_group.py
  src/kfactory/kcell.py
  src/kfactory/layout.py
  src/kfactory/port.py
  src/kfactory/ports.py
  src/kfactory/protocols.py
  tests/test_cell.py
  tests/test_cross_section.py
  tests/test_dkcell.py
  tests/test_port.py
  tests/test_ports.py
Labels: typing

#679 Add Schema and Netlist for Schematic Cells and Extraction
  .pre-commit-config.yaml
  src/kfactory/__init__.py
  src/kfactory/instance.py
  src/kfactory/kcell.py
  src/kfactory/layout.py
  src/kfactory/netlist.py
  src/kfactory/port.py
  src/kfactory/routing/__init__.py
  src/kfactory/routing/generic.py
  src/kfactory/routing/length_functions.py
  src/kfactory/schema.py
  src/kfactory/serialization.py
  src/kfactory/typings.py
  tests/test_layout.py
  tests/test_schema.py
Labels: documentation, enhancement, routing

#706 add basic lvs equivalency checks
  src/kfactory/decorators.py
  src/kfactory/kcell.py
  src/kfactory/layout.py
  src/kfactory/netlist.py
  src/kfactory/schema.py
  tests/test_schema.py
Labels: enhancement

#710 fix property name for lvs_equivalent_ports
  src/kfactory/kcell.py
Labels: bug

#711 Fix schema serialization check and fix pydantic warning
  src/kfactory/netlist.py
  src/kfactory/schema.py
Labels: bug

#714 update docstrings to netlist/schema classses
  docs/mkdocs.yml
  pyproject.toml
  src/kfactory/netlist.py
  src/kfactory/schema.py
  uv.lock
Labels: bug

#715 fix electrical extraction for unnamed cells
  src/kfactory/kcell.py
Labels: bug

#717 Add create_port overload
  src/kfactory/ports.py
Labels: enhancement

#718 Typing Fixes
  pyproject.toml
  src/kfactory/__init__.py
  src/kfactory/schema.py
  uv.lock
Labels: typing
