Repository gdsfactory/kfactory, pull requests merged in 2025-09, with the labels that each got.

#780 better waypoint errors
  src/kfactory/routing/electrical.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  tests/test_routing.py
Labels: bug, routing

#791 Fix typo in ports error
  src/kfactory/ports.py
Labels: bug

#746 better schematic cells
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/pages.yml
  .github/workflows/test.yml
  .gitignore
  docs/mkdocs.yml
  docs/scripts/gen_diagrams.py
  docs/scripts/gen_ref_pages.py
  docs/source/notebooks/05_Schemas.py
  pyproject.toml
  src/kfactory/__init__.py
  src/kfactory/instance.py
  src/kfactory/instance_ports.py
  src/kfactory/kcell.py
  src/kfactory/layout.py
  src/kfactory/netlist.py
  src/kfactory/ports.py
  src/kfactory/schema.py
  src/kfactory/schematic.py
  src/kfactory/typings.py
  tests/test_gdsfactory.py
  tests/test_schematic.py
Labels: enhancement, github_actions

#797 fix router erroring if the ports are not manhattan
  src/kfactory/routing/generic.py
Labels: bug, routing

#800 support pre-releases and other PEP440 conform versions
  pyproject.toml
Labels: maintenance

#801 Improve Schemtics (fix, enhance, change) behaviors
  src/kfactory/cross_section.py
  src/kfactory/factories/virtual/straight.py
  src/kfactory/factories/virtual/utils.py
  src/kfactory/instance.py
  src/kfactory/netlist.py
  src/kfactory/schematic.py
Labels: bug, enhancement

#805 fix connectivity check for cells with text
  src/kfactory/kcell.py
Labels: bug
