Repository gdsfactory/kfactory, pull requests merged in 2025-04, with the labels that each got.

#662 proof of concept for session loading/storing
  src/kfactory/__init__.py
  src/kfactory/conf.py
  src/kfactory/decorators.py
  src/kfactory/kcell.py
  src/kfactory/layout.py
  src/kfactory/protocols.py
  src/kfactory/session_cache.py
  src/kfactory/typings.py
  tests/test_dkcell.py
Labels: enhancement

#658 Session Storage
  src/kfactory/__init__.py
  src/kfactory/conf.py
  src/kfactory/decorators.py
  src/kfactory/kcell.py
  src/kfactory/layout.py
  src/kfactory/protocols.py
  src/kfactory/serialization.py
  src/kfactory/session_cache.py
  src/kfactory/typings.py
  tests/test_dkcell.py
  uv.lock
Labels: enhancement

#664 fix session loading
  src/kfactory/session_cache.py
Labels: bug

#665 missing coverage for sessions
  .pre-commit-config.yaml
  src/kfactory/decorators.py
  src/kfactory/layout.py
  src/kfactory/session_cache.py
  tests/session/__init__.py
  tests/session/py.typed
  tests/session/session1.py
  tests/session/session2.py
  tests/session/session3.py
  tests/test_session.py
Labels: github_actions, cicd

#668 add better error message on none return and support partials
  src/kfactory/decorators.py
  tests/test_cell.py
Labels: enhancement

#670 Fix kcell func prune
  src/kfactory/decorators.py
Labels: bug

#672 Make `@cell` return the `__call__` from the class instead of the entire class
  src/kfactory/layout.py
  tests/test_cell.py
  tests/test_session.py
Labels: bug

#674 relax scipy requirement
  pyproject.toml
  uv.lock
Labels: bug

#676 Add ProtoPort.icenter
  src/kfactory/port.py
  tests/test_port.py
  uv.lock
Labels: enhancement

#677 fix lyrdb generation in route errors
  src/kfactory/routing/generic.py
Labels: bug, routing

#681 Add codeowners file
  .github/CODEOWNERS
Labels: enhancement

#682 better port exceptions
  src/kfactory/exceptions.py
  src/kfactory/instance.py
  tests/test_ports.py
Labels: bug, documentation

#680 better message for off-grid references
  src/kfactory/decorators.py
  src/kfactory/routing/optical.py
Labels: documentation, routing

#685 Run red knot
  .github/workflows/test_code.yml
  uv.lock
Labels: github_actions

#684 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
Labels: documentation, enhancement, github_actions

#686 add route_bundle_rf for electrical
  src/kfactory/routing/electrical.py
  src/kfactory/routing/generic.py
  tests/test_routing.py
Labels: enhancement, routing

#687 fix the rf router
  src/kfactory/routing/electrical.py
  tests/test_routing.py
Labels: bug, routing

#688 Remove codecov patch action
  .github/codecov.yml
  uv.lock
Labels: github_actions

#689 fix rf bboxes being ignored
  src/kfactory/routing/electrical.py
  tests/test_routing.py
Labels: bug, routing

#690 Lower mkdocs video lower bound
  pyproject.toml
  uv.lock
Labels: bug, documentation

#691 fix cache pruning
  src/kfactory/decorators.py
  src/kfactory/layout.py
Labels: bug
