Repository gdsfactory/kfactory, pull requests merged in 2025-06, with the labels that each got.

#720 rework the optical placer and add sbend capabilities
  .pre-commit-config.yaml
  src/kfactory/exceptions.py
  src/kfactory/factories/__init__.py
  src/kfactory/instance.py
  src/kfactory/instance_group.py
  src/kfactory/port.py
  src/kfactory/routing/electrical.py
  src/kfactory/routing/manhattan.py
  src/kfactory/routing/optical.py
  tests/test_pdk.py
  tests/test_routing.py
  tests/test_schema.py
Labels: enhancement, routing

#728 fix routing if no sbend is allowed
  src/kfactory/routing/manhattan.py
Labels: bug, routing

#730 fix replace on being locked when converting cells
  src/kfactory/kcell.py
Labels: bug

#731 add better test for array instances and ports
  tests/test_instance.py
  uv.lock
Labels: enhancement, github_actions, cicd

#732 Add instance pins
  src/kfactory/decorators.py
  src/kfactory/instance.py
  src/kfactory/instance_pins.py
  src/kfactory/kcell.py
  src/kfactory/layout.py
  src/kfactory/pin.py
  src/kfactory/pins.py
  src/kfactory/port.py
  src/kfactory/ports.py
  src/kfactory/typings.py
  src/kfactory/utilities.py
Labels: enhancement

#734 Fix typing issues
  pyproject.toml
  src/kfactory/conf.py
  src/kfactory/decorators.py
  src/kfactory/exceptions.py
  src/kfactory/instance.py
  src/kfactory/kcell.py
  src/kfactory/layer.py
  src/kfactory/port.py
  src/kfactory/routing/length_functions.py
  src/kfactory/typings.py
  src/kfactory/utilities.py
  tests/conftest.py
  tests/custom/show.py
  tests/test_cell.py
  tests/test_config.py
  uv.lock
Labels: bug, routing

#735 fix type completions for jedi
  src/kfactory/layout.py
Labels: bug

#736 fix VInstance trans on insert
  src/kfactory/instance.py
Labels: bug

#737 fix basename/function_name not set on vinst insert
  src/kfactory/instance.py
Labels: bug

#739 fix missing transformation string appending
  src/kfactory/instance.py
Labels: bug

#740 fix netlist extraction for vcells
  src/kfactory/kcell.py
Labels: bug
